from fastapi import APIRouter, UploadFile, File, Depends, Form
from fastapi.responses import StreamingResponse
from motor.motor_asyncio import AsyncIOMotorDatabase
from pydantic import BaseModel
from typing import Optional
import json
import asyncio
from datetime import datetime

from agent.agent import create_agent, create_chat_agent
from agent.document_agent import create_document_agent
from agent.result_types import DocumentProcessingResult
from app.database import get_database

router = APIRouter(prefix="/api/v1", tags=["Phase 3"])


class ChatRequest(BaseModel):
    message: str
    conversation_id: Optional[str] = None


@router.post("/invoices", response_model=DocumentProcessingResult)
async def upload_invoice(
    file: UploadFile = File(...),
    db: AsyncIOMotorDatabase = Depends(get_database),
):
    """Upload and process an invoice document (PDF or image).

    The document is passed directly to the Pydantic AI agent using BinaryContent,
    enabling multimodal processing without intermediate OCR.
    """
    contents = await file.read()

    agent = create_document_agent(db)

    from pydantic_ai.messages import UserPromptPart
    from pydantic_ai import BinaryContent

    user_content = [
        UserPromptPart(
            content="Please analyze this invoice document and extract the relevant information.",
        ),
        BinaryContent(
            data=contents, media_type=file.content_type or "application/octet-stream"
        ),
    ]

    result = await agent.run(user_content, deps=db)

    response = result.output
    response.filename = file.filename or "unknown"

    return response


@router.post("/chat/")
async def chat_stream(
    chat_request: ChatRequest,
    db: AsyncIOMotorDatabase = Depends(get_database),
):
    """Streaming chat endpoint using Server-Sent Events (SSE).

    Returns a StreamingResponse that yields SSE-formatted chunks as they're
    generated by the agent, minimizing Time to First Token (TTFT).
    """
    agent = create_chat_agent(db)

    async def generate():
        async with agent.run_stream(chat_request.message, deps=db) as response:
            async for chunk in response.stream():
                if hasattr(chunk, "content"):
                    yield f"data: {json.dumps({'token': chunk.content})}\n\n"
                elif isinstance(chunk, str):
                    yield f"data: {json.dumps({'token': chunk})}\n\n"
                await asyncio.sleep(0)

            final_data = {
                "done": True,
                "conversation_id": chat_request.conversation_id or "new",
            }
            yield f"data: {json.dumps(final_data)}\n\n"

    return StreamingResponse(
        generate(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no",
        },
    )


@router.get("/health")
async def health_check():
    """Health check endpoint."""
    return {
        "status": "healthy",
        "timestamp": datetime.utcnow().isoformat(),
        "phase": "Phase 3 - Network & Frontend Integration",
    }
